// This guess the number game is a short TypeScript/Node.js project that allows the user to guess the number generated by the computer. There are also several ways to alter the game, like adding more rounds or displaying the score. It’s quite simple and uses the random function to generate a number.
// Create a GitHub repository for the project and submit its URL in the project submission form.
import inquirer from "inquirer";
let pcNumb = Math.ceil(Math.random() * 100);
console.log(pcNumb);
let attempt = 0;
let total = 11;
while (attempt !== total) {
    console.log(attempt);
    if (attempt === 10) {
        console.log("loss");
        break;
    }
    let user = await inquirer.prompt([
        {
            name: "guessnumuser",
            message: "Guessing the number between 1 to 100",
            type: "number"
        }
    ]);
    if (pcNumb > user.guessnumuser) {
        attempt++;
        console.log("Enter greater number");
    }
    else if (pcNumb < user.guessnumuser) {
        attempt++;
        console.log("Enter lesser number");
    }
    else if (pcNumb === user.guessnumuser) {
        attempt++;
        console.log("you won!");
        console.log(`After ${attempt} attempt,you guessed the right answer`);
        console.log(`The answer is ${pcNumb}`);
        break;
    }
}
